# Generated by Django 4.0.4 on 2022-05-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_completed',
            field=models.IntegerField(default=0),
        ),
    ]
