# Generated by Django 4.0.4 on 2022-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
