# Generated by Django 4.0.4 on 2022-05-27 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_program_specialisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('cover_img', models.ImageField(default='notes/images/default.jpg', upload_to='notes/images/')),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='notes/files/')),
                ('total_ratings', models.CharField(default=0, max_length=254)),
                ('num_ratings', models.CharField(default=0, max_length=254)),
                ('downloads', models.CharField(default=0, max_length=254)),
                ('tags', models.TextField(blank=True)),
                ('verified', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('school_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='main.schoollevel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='main.subject')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
