# Generated by Django 4.0.4 on 2022-05-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='uploader',
            new_name='owner',
        ),
    ]
