# Generated by Django 4.0.4 on 2022-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='num_ratings',
            field=models.IntegerField(default=0, max_length=254),
        ),
    ]
