# Generated by Django 4.0.4 on 2022-05-31 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_note_num_ratings_alter_note_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='notes_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
