# Generated by Django 4.0.4 on 2022-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_average_rating_note_slug_note_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
