# Generated by Django 4.0.4 on 2022-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_program_specialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
