# Generated by Django 4.0.4 on 2022-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students_alter_module_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_ratings',
            field=models.IntegerField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='course',
            name='total_ratings',
            field=models.FloatField(default=0.0, max_length=254),
        ),
    ]
