# Generated by Django 4.0.4 on 2022-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_num_ratings_course_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
