# Generated by Django 4.0.4 on 2022-06-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(default='courses/images/default.jpg', upload_to='courses/images/'),
        ),
    ]
