# Generated by Django 4.0.4 on 2022-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='verified',
            field=models.IntegerField(default=1),
        ),
    ]
