# Generated by Django 4.0.4 on 2022-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
