# Generated by Django 4.0.4 on 2022-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
