# Generated by Django 4.0.4 on 2022-06-02 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_alter_quiz_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='quiz_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
