# Generated by Django 4.0.4 on 2022-05-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='discussion_topic',
        ),
    ]
