# Generated by Django 4.0.4 on 2022-05-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_rename_topic_post_discussion_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replie',
            old_name='reply_content',
            new_name='replie_content',
        ),
    ]
