# Generated by Django 4.0.4 on 2022-05-29 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_program_specialisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0004_alter_discussiontopic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiontopic',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='main.schoollevel'),
        ),
    ]
