# Generated by Django 4.0.4 on 2022-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_alter_discussiontopic_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussiontopic',
            name='number_of_posts',
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replie',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
