# Generated by Django 4.0.4 on 2022-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_alter_discussiontopic_verified_alter_post_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
