# Generated by Django 4.0.4 on 2022-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_discussiontopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
